In [1]:
import numpy as np
from time import time
from driver import Model

In [2]:
myip = Model("bitstream/cnn.bit")

In [3]:
import pandas as pd
data = pd.read_csv('Dataset/grenade24.csv', sep=',', header=None)
data = np.int16(data).reshape(-1, 6)
print(data)
gold_result = 2

[[ -3661  -1357  -1258   1586    -61   -440]
 [ -3654  -1366  -1251   1844   -125   -321]
 [ -3653  -1370  -1246   1937   -149   -360]
 [ -3656  -1375  -1242   1935   -185   -401]
 [ -3660  -1380  -1230   1877   -134   -447]
 [ -3678  -1408  -1216   1910    -77   -505]
 [ -3702  -1440  -1200   2073   -117   -631]
 [ -3742  -1485  -1176   2340    -99   -748]
 [ -3840  -1588  -1138   2934    -44   -805]
 [ -4011  -1763  -1085   3955    -57   -843]
 [ -4229  -1970  -1004   5147   -523  -1451]
 [ -4455  -2141   -920   5953  -1642  -2930]
 [ -4621  -2231   -861   5800  -2681  -4519]
 [ -4705  -2269   -828   5114  -2979  -5740]
 [ -4753  -2309   -797   4697  -2850  -6444]
 [ -4785  -2358   -751   4697  -3039  -6767]
 [ -4770  -2427   -703   4830  -3513  -6934]
 [ -4708  -2486   -655   5178  -3890  -7150]
 [ -4620  -2530   -609   5564  -3980  -6975]
 [ -4549  -2640   -547   6065  -4016  -6577]
 [ -4495  -2763   -447   6769  -4487  -6825]
 [ -4424  -2795   -349   6847  -5350  -7577]
 [ -4335  

In [4]:
# sliding window with window size 15, stride 5
data_length = len(data)
window_size = 15
window_stride = 5

highest_false_positive_confidence = 0

for j in range(0, data_length - window_size + 1, window_stride):
    predicted, softmax_confidence = myip.inference(data[j:j + window_size].flatten())
#     print(f"raw outputs: {myip.raw_outputs}")
    print(f"prediction: {predicted} vs GOLD: {gold_result} with confidence {softmax_confidence * 100}%")
    print(f"remaining number of frames required to fill the CNN window: {int(myip.register_map.data_required)}")
    print("\n")

    if predicted != gold_result and softmax_confidence > highest_false_positive_confidence:
        highest_false_positive_confidence = softmax_confidence
myip.resetBuffer()

# if the confidence goes higher than this value then we do not need any more input
print(f"best threshold = {highest_false_positive_confidence*100}%")

prediction: 1 vs GOLD: 2 with confidence 39.951494336128235%
remaining number of frames required to fill the CNN window: 12


prediction: 1 vs GOLD: 2 with confidence 37.77216374874115%
remaining number of frames required to fill the CNN window: 11


prediction: 1 vs GOLD: 2 with confidence 36.404940485954285%
remaining number of frames required to fill the CNN window: 10


prediction: 0 vs GOLD: 2 with confidence 37.584084272384644%
remaining number of frames required to fill the CNN window: 9


prediction: 0 vs GOLD: 2 with confidence 45.8979070186615%
remaining number of frames required to fill the CNN window: 8


prediction: 0 vs GOLD: 2 with confidence 56.01465106010437%
remaining number of frames required to fill the CNN window: 7


prediction: 0 vs GOLD: 2 with confidence 57.37592577934265%
remaining number of frames required to fill the CNN window: 6


prediction: 0 vs GOLD: 2 with confidence 62.02477216720581%
remaining number of frames required to fill the CNN window: 5


pre