In [1]:
import numpy as np
from time import time
from driver import Model

In [2]:
myip = Model("bitstream/cnn.bit")

In [3]:
# newCNNWeights=np.array([-0.040779676, 0.11799976, 0.08973799, -0.14907303, 0.12589113, -0.015012624, -0.033560883, 0.20321637, 0.12930135, 0.07037665, -0.11672246, -0.111203976, -0.16173074, 0.004696705, 0.055634473, -0.026748983, 0.013060051, -0.08739026, -0.0366215, -0.03320449, 0.04473737, -0.14353774, -0.15560016, 0.16841319, -0.00030443427, 0.030196916, 0.11797808, 0.12667589, -0.01699022, 0.03877313, 0.112717316, 0.047185767, -0.033790696, -0.17041782, 0.044985525, 0.16690293, 0.109396756, 0.07134988, 0.18340589, -0.1185263, 0.18496862, 0.06689047, -0.014098875, -0.11152336, 0.15501978, -0.049174167, 0.063270114, 0.14097166, 0.031158447, 0.16460213, -0.062205188, -0.048170887, 0.13438264, -0.03932296, 0.116147384, -0.110271364, 0.05113533, -0.078996144, -0.035803087, 0.017977607, 0.119513445, -0.015368759, -0.046699964, -0.09136006, 0.11680877, 0.12899312, 0.03195804, 0.10274496, -0.07662395, -0.021048225, 0.09620437, 0.045011498, -0.15756182, -0.017677227, 0.09504748, 0.11700831, 0.15698397, 0.030095385, -0.08727767, -0.064398, -0.08136118, -0.07508109, -0.00042843205, -0.057625916, 0.014332805, 0.14746724, 0.15857328, 0.20953141, -0.11301991, 0.08957523, 0.11225233, 0.12466457, 0.104845576, -0.13916157, -0.07934091, 0.11289415, 0.0714135, 0.0071795923, -0.048239138, 0.11784856, 0.17714053, 0.030575743, 0.034067072, -0.015727969, 0.03736375, -0.15245067, 0.021852463, 0.053997234, -0.03612787, 0.17623411, -0.12813199, -0.073952496, -0.06578716, 0.126257, 0.06316354, 0.0010890275, -0.14534749, 0.10552647, -0.066009104, -0.08703051, 0.08190686, -0.081753954, -0.13015181, -0.018157752, -0.09973657, -0.001862305, 0.05916203, 0.03541004, -0.103318624, -0.08209472, 0.11256827, -0.1009504, -0.07329098, 0.14211266, 0.014404967, -0.14271733, -0.102062285, 0.13668, -0.09467104, -0.081254505, 0.09375034, -0.08278621, -0.21244593, 0.13937669, 0.13499278, 0.16283156, 0.16997215, 0.2020627, 0.14221993, -0.15000275, 0.067715436, 0.06794258, 0.0625149, -0.18203582, -0.16047364, 0.07808437, -0.053249367, -0.11116418, -0.018037237, -0.1338895, 0.07956265, -0.109440066, 0.093695335, 0.1735906, -0.027543474, -0.03423494, -0.072754726, -0.009909152, 0.094883725, 0.13915414, -0.050389934, 0.04746809, -0.05318063, -0.011380505, 0.13742813, -0.02587133, 0.05139914, 0.0806891, 0.12079502, -0.055656716, 0.13825351, 0.12985998, -0.04807272, 0.12622333, -0.058589365, -0.034980886, -0.10997298, 0.12781808, 0.09177162, 0.05975846, -0.12507077, 0.017304681, 0.03701113, 0.025885377, -0.044328626, 0.09956908, -0.049434084, 0.08419951, -0.069917515, -0.047699112, 0.015983015, -0.18850279, -0.0870574, 0.07422233, -0.07697351, -0.0154107, -0.017779937, 0.07222376, 0.043063566, -0.14026521, 0.063792884, -0.16750588, -0.1855945, -0.060607884, 0.07701398, -0.11504946, 0.14524041, 0.015292845, 0.0027797667, -0.022019569, -0.10321901, 0.14283329, 0.03973537, -0.051544126, 0.09104316, 0.0845512, 0.13454114, 0.13971664, 0.06805527, -0.06488202, -0.012816272, -0.0152718555, -0.06038757, 0.033469975, 0.05660585, -0.16319016, 0.00759642, 0.08452792, -0.075145975, -0.08409914, -0.029181888, 0.081982315, -0.08580748, -0.023316093, 0.11933734, 0.022255378, 0.012973753, 0.04195805, -0.1503654, 0.13337664, -0.1063235, -0.0607534, -0.112944104, -0.14321333, 0.115709774, -0.04631358, 0.1095302, -0.101777665, -0.03981526, -0.026476422, -0.07802481, -0.036395956, -0.031814653, -0.09203105, 0.13572682, 0.02181997, -0.02672551, 0.20864438, -0.00614808, -0.04596181, 0.14978169, -0.105934314, 0.043729093, -0.17089933, -0.017218279, 0.17900102, -0.062288232, -0.13627128, -0.02521294, 0.06163718, 0.119082965, 0.04799089, 0.04448919, 0.0043980684, 0.12761612, 0.05131863, 0.00020710453, 0.02120705, 0.17045411, 0.03735442, 0.012272676, -0.045579877, 0.0041832016, 0.08266779, -0.039458405, -0.1323672, -0.07383744, 0.05856017, -0.05161067, -0.052546114, 0.06851246, 0.009251332, -0.042137686, -0.13894282, 0.051421396, -0.0684027, 0.077647224, 0.088240355, 0.10448642, 0.16815718, 0.04413311, -0.12896937, -0.18983638, 0.01864927, 0.045068346, -0.08477182, -0.023242395, 0.14923882, 0.1450569, 0.06981466, 0.15060176, -0.08656679, -0.06721364, -0.051111832, 0.064114675, 0.20795129, 0.18391797, -0.015639983, 0.010581363, -0.0010051312, -0.100440815, -0.16415188, 0.010090468, -0.00045630973, 0.09157319, 0.013798704, -0.1492421, 0.02118864, -0.0987959, -0.12435405, -0.10865356, -0.07711708, -0.109037705, -0.10674451, 0.05665456, -0.051988333, -0.06927692, 0.096952885, 0.06492147, -0.10727254, 0.0985227, -0.0029595157, -0.0070932335, 0.0996868, 0.15978603, -0.1795693, 0.08837687, -0.017403914, 0.087684795, 0.07383404, 0.11690405, -0.08804755, 0.11402403, 0.013608089, -0.06957385, 0.12137934, -0.094555765, 0.009247006, -0.0528814, 0.16748227, 0.05677429, 0.1078705, -0.17847739, -0.17343959, 0.08608615, 0.038219906, 0.046633597, 0.01621768, 0.07541279, -0.123844974, -0.050909482, -0.10894415, -0.07494804, -0.07773671, 0.037733193, 0.22922985, -0.066821344, -0.04116128, -0.054623615, -0.011971232, 0.1774997, -0.038299985, 0.06432611, -0.016186599, 0.1091686, 0.08685014, -0.10261401, 0.13229398, 0.006128395, -0.08371372, 0.08843873, 0.058240384, 0.13673438, 0.14236626, -0.057680406, -0.041816413, 0.07746307, 0.10818064, 0.12238777, 0.112424076, 0.084252484, 0.15017036, 0.04806566, -0.17992027, 0.07117243, -0.0007598642, 0.053330492, 0.0031949691, -0.056188025, -0.1020717, 0.112420246, 0.017966999, 0.04020389, 0.031664792, 0.12692252, 0.18098834, 0.15699473, 0.14069384, -0.09212383, 0.094967574, -0.10161778, -0.057817828, -0.19337395, 0.047369663, 0.10178086, 0.13099846, -0.07909185, 0.054988302, -0.115689114, -0.12424354, 0.18699561, -0.014963328, -0.16026698, 0.1673632, 0.08747259, 0.1901904, -0.059142597, 0.0075684125, -0.08797585, 0.041766845, -0.0714419, 0.12669556, -0.0035672183, 0.014056897, 0.08378651, 0.021079596, -0.099024974, 0.0014232587, 0.18979098, -0.032720048, 0.17920767, -0.007334558, -0.054264214, 0.14038593, 0.013852577, -0.016981276, -0.000362595, 0.095678315, 0.07662087, 0.09603908, -0.19140291, 0.128083, 0.033424553, 0.099373855, 0.008864054, 0.03884942, -0.116530076, 0.14143161, -0.07357086, 0.043446884, -0.10249427, 0.11889259, 0.16009441, -0.13876276, -0.119756125, 0.13307199, 0.1494492, -0.06448678, 0.028701665, -0.06824465, -0.12464538, -0.0072974614, -0.0057166126, -0.076753706, -0.060747307, 0.0168777, -0.025711652, -0.041340165, 0.1574397, -0.027347771, 0.16888772, 0.039643746, 0.024807543, 0.050571643, 0.05599783, 0.13058682, -0.09209017, 0.08858647, -0.06604856, 0.04433539, -0.08684087, 0.06741976, 0.089970976, -0.15932474, -0.092597686, -0.050754495, -0.0013838646, 0.027752427, 0.18505599, -0.10932594, 0.07836228, 0.11569123, -0.045686446, -0.06835837, 0.09952542, 0.023202583, 0.1263365, -0.034102593, -0.08828023, -0.08499517, -0.11183351, 0.06806961, 0.02095091, -0.15082817, 0.087543964, -0.14309452, 0.014028961, 0.1945418, -0.18046468, -0.15880051, 0.12490017, 0.14693242, 0.13799599, 0.11979588, 0.15878724, 0.15997377, -0.11804985, -0.11048165, 0.08749915, -0.03278671, 0.071853116, -0.08525819, 0.07546522, -0.041310556, 0.12492258, -0.14746083, 0.103748865, -0.10221068, -0.10122668, 0.10939802, 0.0355157, -0.18020537, 0.073694095, 0.039748315, -0.00560773, 0.04521227, 0.093481496, 0.15582807, -0.120977424, -0.12033242, -0.019166997, 0.0038480673, -0.15265113, -0.052822, 0.0028131278, -0.08126372, -0.11339026, -0.044841062, -0.11148492, 0.105424546, -0.07933218, 0.101450436, -0.09438638, -0.07769817, 0.14994432, -0.005527929, 0.11910377, 0.11421107, 0.14285474, 0.06859134, -0.058377977, 0.08824884, 0.06340691, 0.019437037, 0.08407126, -0.12328174, 0.004238993, 0.04955657, 0.0063141887, 0.079707496, -0.06261569, 0.019091202, -0.11633635, -0.029039592, -0.081443086, 0.025459105, 0.082397036, 0.1388367, -0.0015137512, -0.083188646, -0.15674916, 0.052000623, -0.114057265, -0.079264484, -0.041556057, -0.1541298, 0.014568253, 0.0620059, 0.13734777, -0.11746314, -0.11906907, -0.009427807, -0.16011724, 0.144922, -0.016593777, 0.12730901, -0.08416501, 0.1802122, -0.0746274, -0.1815102, -0.07475062, 0.01145461, -0.05701598, -0.054593462, 0.12921144, -0.08500136, -0.070076786, 0.00822616, 0.14099057, -0.0910144, -0.12030919, 0.05325546, 0.045525894, 0.0068494207, -0.11478515, 0.009264657, -0.15215275, 0.123210415, 0.17094591, -0.088539675, 0.06084757, 0.16756842, -0.12207158, -0.05449845, 0.094682574, -0.007322082, -0.09142334, -0.067102306, -0.17454782, -0.100592695, -0.012256896, 0.14012077, 0.14253353, -0.028765751, 0.16024233, 0.18177448, 0.18880759, 0.055236213, 0.0732777, 0.028401628, 0.07771492, -0.16192509, -0.12357296, -0.1381531, -0.040091306, 0.13220721, -0.09972538, -0.08928044, -0.0994403, -0.08032276, -0.053475253, -0.20403332, -0.11818874, 0.094583355, -0.04791994, -0.04355511, 0.112889774, 0.17652594, 0.08693605, -0.13102865, -0.052890863, -0.06404985, -0.09869299, -0.18442681, -0.1374421, 0.02324021, 0.08860783, -0.0037976892, 0.038431972, -0.09754483, -0.11089903, -0.022141622, -0.10721366, -0.11422605, 0.02667036, -0.14864908, -0.059737667, 0.09378547, -0.103604466, 0.036472455, -0.17866024, 0.15338376, 0.04313528, -0.06273227, 0.053537447, 0.121875286, 0.023920782, 0.118448585, 0.025210446, -0.01696871, 0.035978563, 0.14445248, 0.05958636, -0.109594084, 0.10040965, 0.015557942, -0.09179423, -0.021667246, 0.020022344, 0.05918156, -0.00921006, -0.026775813, 0.08294058, -0.01780279, 0.11624776, -0.061028298, -0.027960107, 0.05145186, -0.020860938, -0.030941462, 0.15285215, -0.054059055, -0.14249547, 0.08921071, -0.012462726, 0.06139933, 0.088394515, 0.1624854, 0.10519005, -0.1689088, -0.019374147, 0.031348478, -0.112221085, 0.07692418, -0.030581202, -0.06783595, -0.03526142, -0.04114645, 0.06940793, 0.02081182, -0.06996453, -0.0012514387, 0.11316117, 0.15077013, 0.1552173, -0.18725629, -0.0014002951, -0.051180534, -0.08588114, 0.073151, 0.04520635, 0.030135902, 0.0060031516, 0.021921413, -0.07548947, 0.14231034, 0.020588635, 0.1895643, 0.10445862, -0.15312076, -0.1259519, -0.036257405, 0.115201235, 0.05291973, -0.12726259, 0.14109792, -0.067611046, -0.13119061, 0.07962764, 0.16800985, 0.00061916414, 0.10597829, -0.013582304, 0.012767532, -0.08881968, 0.11064653, -0.048790492, 0.14297882, 0.06094144, 0.10616309, -0.055900265, 0.08136011, 0.03975438, 0.1108063, -0.063337795, 0.022240536, 0.01753317, -0.041184552, 0.08569639, -0.123028025, 0.1377206, -0.0034967763, -0.15881383, 0.08897975, -0.121882915, -0.0044640987, 0.11219826, 0.121293165, -0.044440523, 0.14446309, -0.02306232, 0.007389282, 0.01593436, 0.16918093, 0.101956874, -0.112670906, -0.03681093, 0.07595351, 0.06289578, 0.14511248, 0.1112994, 0.10422632, 0.073154226, 0.085035786, -0.060918543, -0.0016813307, 0.048442926, -0.030298317, 0.11879235, 0.015586591, 0.10790888, -0.006155595, -0.09587764, -0.13468929, 0.07330274, 0.18477951, 0.1483722, 0.06627719, -0.12460763, 0.008239994, -0.126402, 0.13306274, -0.16339526, -0.023408556, 0.030747574, 0.1329804, 0.09542725, -0.14718704, 0.0046845977, -0.07692062, 0.061748877, -0.060653884, 0.018478502, 0.09899009, 0.10073482, 0.03133943, -0.090766825, 0.17039886, 0.046430495, -0.074751996, 0.13204665, -0.14152472, -0.15509696, -0.08956305, -0.14294115, 0.077905186, 0.016183164, -0.040560596, 0.103930406, 0.0919885, 0.10324764, -0.02825957, -0.08711388, -0.0842252, 0.16697407, -0.17101748, 0.06675263, 0.13157673, -0.101777636, 0.050287317, 0.054988027, 0.016224539, 0.07306805, -0.118196815, -0.07394875, 0.038971297, -0.12207305, -0.045392163, -0.09407876, 0.07710193])
# newCNNBias=np.array([0.005610074, -0.023800611, 0.04052538, -0.012903892, -0.025943663, 0.04185619, 0.00026216602, 0.014545479, -0.015855083, 0.010001008])
# newDenseWeights=np.array([-0.102392934, 0.13667202, 0.09079784, -0.31457725, 0.20443036, -0.109824814, -0.13456245, 0.26460367, 0.1418402, -0.052161507, -0.06766398, -0.20514794, -0.120893136, -0.006464043, 0.0033036412, -0.06534647, -0.052820817, -0.08824818, -0.08317097, 0.016261421, 0.022554431, -0.17095025, -0.15477344, 0.24457422, -0.015883781, -0.07022673, 0.114593245, 0.039721843, 0.016978666, 0.059677754, 0.06874102, 0.103473835, 0.019333353, -0.24462539, 0.1326096, 0.1435461, 0.05731251, 0.1692871, 0.12015718, -0.27236664, 0.25754324, 0.013958425, -0.05276121, -0.2144127, 0.16037834, -0.13665046, 0.06389821, 0.2648123, 0.049694445, 0.12533408, -0.049822185, -0.18978287, 0.05146886, 0.020624643, 0.1797478, -0.14799698, 0.04445662, -0.11018585, 0.026397597, -0.027093591, 0.16654381, -0.06611427, -0.10465842, -0.1989417, 0.17615108, 0.081718475, -0.0595047, 0.12877256, -0.10992024, -0.14262474, 0.14439616, 0.0885556, -0.14110531, 0.008784672, 0.059876837, 0.11015728, 0.14092802, 0.093394145, -0.10778614, -0.048013166, -0.1607544, -0.10143425, 0.013139026, -0.026547961, 0.06548118, 0.057200048, 0.11443443, 0.17655468, -0.09800203, 0.09680063, 0.13018286, 0.19693375, 0.17375422, -0.19095981, -0.057339888, 0.0982819, 0.024474278, 0.065114506, -0.17486127, 0.033795547, 0.2293178, 0.054877557, -0.04104804, -0.052121565, -0.0018259817, -0.19347918, 0.024354298, 0.093482845, -0.057724554, 0.14964125, -0.1294285, -0.21015194, -0.19785115, 0.2477431, 0.13188507, 2.7392969e-05, -0.24464278, 0.111635745, -0.024427876, -0.15727821, 0.0937768, -0.11549924, -0.23834684, -0.104086615, -0.1198847, -0.06337208, -0.004035548, 0.055784527, -0.16067523, -0.24318056, 0.16207083, -0.07597553, -0.06674876, 0.18726593, -0.00030576484, -0.120613344, -0.20372805, 0.15648043, -0.15286447, -0.026881507, 0.06269517, -0.07626096, -0.22587326, 0.2049698, 0.20130612, 0.08897183, 0.15077782, 0.19483034, 0.20170464, -0.20442657, 0.081835926, 0.08914403, 0.14041393, -0.25984082, -0.14156541, 0.03129697, -0.13932076, -0.09338162, -0.1434227, -0.2797551, 0.090164915, -0.1157348, 0.03193791, 0.16600862, -0.032964144, -0.006209938, -0.14647685, 0.024402605, 0.092098534, 0.115955524, -0.029835757, -0.0381642, -0.1591863, 0.060829334, 0.17783958, -0.030083243, 0.05349237, 0.060708024, 0.23001416, -0.11159109, 0.13551268, 0.16652808, -0.079851866, 0.091853544, -0.056949113, -0.1085198, -0.16977872, 0.1813892, 0.078061, -0.075405896, -0.08926977, -0.0018348213, 0.06405053, 0.053068276, -0.073467165, 0.14142184, -0.16137262, 0.16015975, -0.13182984, 0.0013829875, -0.02559191, -0.21460477, -0.06433968, 0.13233562, -0.09356329, -0.14194395, -0.12209914, 0.011180333, 0.06572046, -0.18127677, 0.034780372, -0.21736972, -0.19317983, -0.10685091, 0.17616524, -0.17022146, 0.11864522, 0.09103719, -0.116158456, -0.15637793, -0.12990229, 0.19673842, -0.035991587, -0.10667296, 0.09717399, 0.19142433, 0.12762898, 0.19217886, 0.06428897, -0.16515177, 0.012453443, -0.13691367, -0.17334376, 0.13156995, 0.082065366, -0.20241961, -0.038584646, 0.025989084, -0.0024846753, -0.15984054, -0.047741875, 0.073164664, -0.13278387, -0.06313863, 0.14680248, -0.02757656, -0.025889356, 0.059306648, -0.24612631, 0.037511654, -0.07734191, -0.09334045, -0.15016288, -0.13889708, 0.110362366, 0.014332552, 0.04072453, -0.13284107, -0.084202684, 0.018765103, -0.14364687, -0.06357704, -0.03629911, -0.062492523, 0.15989849, -0.08555189, -0.10080359, 0.15219772, 0.02985412, -0.055739485, 0.17829485, -0.14129546, 0.102843575, -0.20670988, 0.042179413, 0.16903453, -0.12552173, -0.099064775, -0.18221204, -0.024281373, 0.1688175, 0.048050825, -0.04148761, -0.042870007, 0.1995845, 0.13147943, -0.06759157, 0.04028028, 0.14290155, -0.013392905, 0.06405466, -0.17665437, -0.106204525, 0.21288596, -0.11689457, -0.16372868, -0.07423288, -0.03376754, 0.039679673, -0.0966597, 0.108655535, -0.051554836, -0.08289707, -0.23909439, 0.07148139, -0.15250315, 0.010153103, 0.16177137, 0.07928317, 0.09053276, 0.125654, -0.19033548, -0.23797801, 0.01312669, 0.06391026, -0.045689397, -0.12872401, 0.168953, 0.16784088, 0.16042928, 0.1390186, -0.08866349, -0.08118172, -0.037302073, -0.008834971, 0.16570655, 0.24718507, -0.16811833, 0.062687084, 0.00015926297, -0.13702206, -0.257652, 0.09600297, -0.042940278, 0.22677492, -0.043914393, -0.23239048, 0.08852466, -0.26030004, -0.28817305, -0.11804299, -0.119605966, -0.23025347, -0.22394578, 0.10113432, 0.012240786, -0.17603596, 0.1435721, -0.004891604, -0.17793214, 0.16198778, -0.01604573, -0.0976767, 0.19365905, 0.13621837, -0.18922286, 0.109371595, -0.10558346, 0.22538286, 0.068422295, 0.09777045, -0.20487386, 0.21415778, -0.08969257, -0.05235258, 0.08188145, -0.20942102, 0.044987254, -0.12827075, 0.08787477, 0.11732938, 0.18753423, -0.22492298, -0.20210296, 0.08876909, 0.1360175, -0.100461304, 0.06633467, 0.08136801, -0.10614159, -0.13761497, -0.08624841, -0.10432541, -0.04853255, -0.030482592, 0.18937445, -0.105366185, -0.16196886, -0.036382005, -0.02001419])
# newDenseBias=np.array([-0.056499984, 0.042923816, -0.026141524])
# myip.setCNNWeights(np.float32(newCNNWeights))
# myip.setCNNBias(np.float32(newCNNBias))
# myip.setDenseWeights(np.float32(newDenseWeights))
# myip.setDenseBias(np.float32(newDenseBias))

In [9]:
import pandas as pd
data = pd.read_csv('Dataset/grenade10.csv', sep=',', header=None)
data = np.int16(data).reshape(-1, 6)
print(data)
gold_result = 2

[[ -4034   -843   -488  -1736   -742  -1051]
 [ -4164   -859   -391  -2111  -1288  -1674]
 [ -4350   -989   -316  -1705  -1817  -2113]
 [ -4593  -1165   -258    456  -2829  -2831]
 [ -4842  -1327   -233   2298  -3890  -3716]
 [ -5106  -1525   -223   3672  -4931  -4866]
 [ -5346  -1632   -199   4544  -5969  -6373]
 [ -5535  -1699   -150   4827  -6874  -7176]
 [ -5724  -1794    -64   5959  -8144  -7438]
 [ -5868  -1901     73   7669  -9679  -7352]
 [ -5946  -2022    217   9234 -11320  -6752]
 [ -5935  -2092    397  10004 -12855  -6394]
 [ -5782  -2030    591   9107 -14383  -6712]
 [ -5470  -1872    757   7139 -15483  -6272]
 [ -5177  -1904   1023   6702 -15169  -4634]
 [ -5027  -2132   1447   6710 -16021  -3946]
 [ -4858  -2409   1838   8165 -18321  -4077]
 [ -4602  -2453   2158   7834 -21613  -5380]
 [ -4182  -2354   2331   5805 -22587  -5754]
 [ -3715  -2179   2356   2930 -22931  -5807]
 [ -3205  -2111   2268   1847 -22582  -5859]
 [ -2840  -2115   2211   2427 -21339  -5925]
 [ -2403  

In [10]:
data_length = len(data)

highest_false_positive_confidence = 0

for j in range(0, data_length):
    predicted, softmax_confidence = myip.inference(data[j])
#     print(f"raw outputs: {myip.raw_outputs}")
    print(f"prediction: {predicted} vs GOLD: {gold_result} with confidence {softmax_confidence * 100}%")
    print("\n")

    if predicted != gold_result and softmax_confidence > highest_false_positive_confidence:
        highest_false_positive_confidence = softmax_confidence
myip.resetBuffer()

# if the confidence goes higher than this value then we do not need any more input
print(f"best threshold = {highest_false_positive_confidence*100}%")

prediction: 0 vs GOLD: 2 with confidence 25.0%


prediction: 0 vs GOLD: 2 with confidence 25.0%


prediction: 2 vs GOLD: 2 with confidence 27.077582478523254%


prediction: 2 vs GOLD: 2 with confidence 26.98121964931488%


prediction: 2 vs GOLD: 2 with confidence 26.88121795654297%


prediction: 2 vs GOLD: 2 with confidence 26.777616143226624%


prediction: 1 vs GOLD: 2 with confidence 26.773831248283386%


prediction: 1 vs GOLD: 2 with confidence 27.255207300186157%


prediction: 1 vs GOLD: 2 with confidence 27.741068601608276%


prediction: 1 vs GOLD: 2 with confidence 28.231343626976013%


prediction: 1 vs GOLD: 2 with confidence 28.725948929786682%


prediction: 1 vs GOLD: 2 with confidence 29.22479212284088%


prediction: 1 vs GOLD: 2 with confidence 29.727786779403687%


prediction: 1 vs GOLD: 2 with confidence 30.234837532043457%


prediction: 1 vs GOLD: 2 with confidence 30.745849013328552%


prediction: 1 vs GOLD: 2 with confidence 31.260710954666138%


prediction: 1 vs GOLD: 