In [1]:
import numpy as np
from time import time
from driver import Model

In [2]:
myip = Model("bitstream/cnn.bit")

In [3]:
myip.setCNNWeights(np.load("CNN_weights.npy"))
myip.setCNNBias(np.load("CNN_bias.npy"))
myip.setDenseWeights(np.load("dense_weights.npy"))
myip.setDenseBias(np.load("dense_bias.npy"))

In [4]:
import pandas as pd
data = pd.read_csv('Dataset/grenade10.csv', sep=',', header=None)
data = np.int16(data).reshape(-1, 6)
print(data)
gold_result = 2

[[ -4034   -843   -488  -1736   -742  -1051]
 [ -4164   -859   -391  -2111  -1288  -1674]
 [ -4350   -989   -316  -1705  -1817  -2113]
 [ -4593  -1165   -258    456  -2829  -2831]
 [ -4842  -1327   -233   2298  -3890  -3716]
 [ -5106  -1525   -223   3672  -4931  -4866]
 [ -5346  -1632   -199   4544  -5969  -6373]
 [ -5535  -1699   -150   4827  -6874  -7176]
 [ -5724  -1794    -64   5959  -8144  -7438]
 [ -5868  -1901     73   7669  -9679  -7352]
 [ -5946  -2022    217   9234 -11320  -6752]
 [ -5935  -2092    397  10004 -12855  -6394]
 [ -5782  -2030    591   9107 -14383  -6712]
 [ -5470  -1872    757   7139 -15483  -6272]
 [ -5177  -1904   1023   6702 -15169  -4634]
 [ -5027  -2132   1447   6710 -16021  -3946]
 [ -4858  -2409   1838   8165 -18321  -4077]
 [ -4602  -2453   2158   7834 -21613  -5380]
 [ -4182  -2354   2331   5805 -22587  -5754]
 [ -3715  -2179   2356   2930 -22931  -5807]
 [ -3205  -2111   2268   1847 -22582  -5859]
 [ -2840  -2115   2211   2427 -21339  -5925]
 [ -2403  

In [6]:
data_length = len(data)

highest_false_positive_confidence = 0

for j in range(0, data_length):
    predicted, softmax_confidence = myip.inference(data[j])
#     print(f"raw outputs: {myip.raw_outputs}")
    print(f"current time = {0.02 * j}s")
    print(f"prediction: {predicted} vs GOLD: {gold_result} with confidence {softmax_confidence * 100}%")
    print("\n")

    if predicted != gold_result and softmax_confidence > highest_false_positive_confidence:
        highest_false_positive_confidence = softmax_confidence
myip.resetBuffer()

# if the confidence goes higher than this value then we do not need any more input
print(f"best threshold = {highest_false_positive_confidence*100}%")

current time = 0.0s
prediction: 0 vs GOLD: 2 with confidence 25.0%


current time = 0.02s
prediction: 0 vs GOLD: 2 with confidence 25.0%


current time = 0.04s
prediction: 3 vs GOLD: 2 with confidence 29.436519742012024%


current time = 0.06s
prediction: 3 vs GOLD: 2 with confidence 30.605462193489075%


current time = 0.08s
prediction: 3 vs GOLD: 2 with confidence 32.10863471031189%


current time = 0.1s
prediction: 3 vs GOLD: 2 with confidence 32.88532793521881%


current time = 0.12s
prediction: 3 vs GOLD: 2 with confidence 32.93183147907257%


current time = 0.14s
prediction: 3 vs GOLD: 2 with confidence 32.62261152267456%


current time = 0.16s
prediction: 3 vs GOLD: 2 with confidence 32.423511147499084%


current time = 0.18s
prediction: 3 vs GOLD: 2 with confidence 32.35580325126648%


current time = 0.2s
prediction: 2 vs GOLD: 2 with confidence 33.23054313659668%


current time = 0.22s
prediction: 2 vs GOLD: 2 with confidence 34.6883088350296%


current time = 0.24s
prediction